//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace TY.ER.ED00.KniaWebRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InsWebServiceImplServiceSoapBinding", Namespace="http://impl.ws.insedi.or.kr/")]
    public partial class InsWebServiceImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getBondedGoodsOutResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveDomesticGoodsOutInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDomesticGoodsInResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveBondedGoodsOutInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveBondedGoodsInInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveDomesticGoodsInInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveBondedGoodsPremiumInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDomesticGoodsOutResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBondedGoodsPremiumResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback sayHiOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveDomesticGoodsPremiumInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBondedGoodsInResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatusDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDomesticGoodsPremiumResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InsWebServiceImplService() {
            this.Url = global::TY.ER.ED00.Properties.Settings.Default.ED00_KniaWebRef_InsWebServiceImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getBondedGoodsOutResultCompletedEventHandler getBondedGoodsOutResultCompleted;
        
        /// <remarks/>
        public event saveDomesticGoodsOutInfoCompletedEventHandler saveDomesticGoodsOutInfoCompleted;
        
        /// <remarks/>
        public event getDomesticGoodsInResultCompletedEventHandler getDomesticGoodsInResultCompleted;
        
        /// <remarks/>
        public event saveBondedGoodsOutInfoCompletedEventHandler saveBondedGoodsOutInfoCompleted;
        
        /// <remarks/>
        public event saveBondedGoodsInInfoCompletedEventHandler saveBondedGoodsInInfoCompleted;
        
        /// <remarks/>
        public event saveDomesticGoodsInInfoCompletedEventHandler saveDomesticGoodsInInfoCompleted;
        
        /// <remarks/>
        public event saveBondedGoodsPremiumInfoCompletedEventHandler saveBondedGoodsPremiumInfoCompleted;
        
        /// <remarks/>
        public event getDomesticGoodsOutResultCompletedEventHandler getDomesticGoodsOutResultCompleted;
        
        /// <remarks/>
        public event getBondedGoodsPremiumResultCompletedEventHandler getBondedGoodsPremiumResultCompleted;
        
        /// <remarks/>
        public event sayHiCompletedEventHandler sayHiCompleted;
        
        /// <remarks/>
        public event saveDomesticGoodsPremiumInfoCompletedEventHandler saveDomesticGoodsPremiumInfoCompleted;
        
        /// <remarks/>
        public event getBondedGoodsInResultCompletedEventHandler getBondedGoodsInResultCompleted;
        
        /// <remarks/>
        public event getStatusDataCompletedEventHandler getStatusDataCompleted;
        
        /// <remarks/>
        public event getDomesticGoodsPremiumResultCompletedEventHandler getDomesticGoodsPremiumResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getBondedGoodsOutResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute("outNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] outNo) {
            object[] results = this.Invoke("getBondedGoodsOutResult", new object[] {
                        id,
                        pass,
                        outNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBondedGoodsOutResultAsync(string id, string pass, string[] outNo) {
            this.getBondedGoodsOutResultAsync(id, pass, outNo, null);
        }
        
        /// <remarks/>
        public void getBondedGoodsOutResultAsync(string id, string pass, string[] outNo, object userState) {
            if ((this.getBondedGoodsOutResultOperationCompleted == null)) {
                this.getBondedGoodsOutResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBondedGoodsOutResultOperationCompleted);
            }
            this.InvokeAsync("getBondedGoodsOutResult", new object[] {
                        id,
                        pass,
                        outNo}, this.getBondedGoodsOutResultOperationCompleted, userState);
        }
        
        private void OngetBondedGoodsOutResultOperationCompleted(object arg) {
            if ((this.getBondedGoodsOutResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBondedGoodsOutResultCompleted(this, new getBondedGoodsOutResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saveDomesticGoodsOutInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string outNo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string data) {
            object[] results = this.Invoke("saveDomesticGoodsOutInfo", new object[] {
                        id,
                        pass,
                        outNo,
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveDomesticGoodsOutInfoAsync(string id, string pass, string outNo, string data) {
            this.saveDomesticGoodsOutInfoAsync(id, pass, outNo, data, null);
        }
        
        /// <remarks/>
        public void saveDomesticGoodsOutInfoAsync(string id, string pass, string outNo, string data, object userState) {
            if ((this.saveDomesticGoodsOutInfoOperationCompleted == null)) {
                this.saveDomesticGoodsOutInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveDomesticGoodsOutInfoOperationCompleted);
            }
            this.InvokeAsync("saveDomesticGoodsOutInfo", new object[] {
                        id,
                        pass,
                        outNo,
                        data}, this.saveDomesticGoodsOutInfoOperationCompleted, userState);
        }
        
        private void OnsaveDomesticGoodsOutInfoOperationCompleted(object arg) {
            if ((this.saveDomesticGoodsOutInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveDomesticGoodsOutInfoCompleted(this, new saveDomesticGoodsOutInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getDomesticGoodsInResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute("inNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] inNo) {
            object[] results = this.Invoke("getDomesticGoodsInResult", new object[] {
                        id,
                        pass,
                        inNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDomesticGoodsInResultAsync(string id, string pass, string[] inNo) {
            this.getDomesticGoodsInResultAsync(id, pass, inNo, null);
        }
        
        /// <remarks/>
        public void getDomesticGoodsInResultAsync(string id, string pass, string[] inNo, object userState) {
            if ((this.getDomesticGoodsInResultOperationCompleted == null)) {
                this.getDomesticGoodsInResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDomesticGoodsInResultOperationCompleted);
            }
            this.InvokeAsync("getDomesticGoodsInResult", new object[] {
                        id,
                        pass,
                        inNo}, this.getDomesticGoodsInResultOperationCompleted, userState);
        }
        
        private void OngetDomesticGoodsInResultOperationCompleted(object arg) {
            if ((this.getDomesticGoodsInResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDomesticGoodsInResultCompleted(this, new getDomesticGoodsInResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saveBondedGoodsOutInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string outNo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string data) {
            object[] results = this.Invoke("saveBondedGoodsOutInfo", new object[] {
                        id,
                        pass,
                        outNo,
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveBondedGoodsOutInfoAsync(string id, string pass, string outNo, string data) {
            this.saveBondedGoodsOutInfoAsync(id, pass, outNo, data, null);
        }
        
        /// <remarks/>
        public void saveBondedGoodsOutInfoAsync(string id, string pass, string outNo, string data, object userState) {
            if ((this.saveBondedGoodsOutInfoOperationCompleted == null)) {
                this.saveBondedGoodsOutInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveBondedGoodsOutInfoOperationCompleted);
            }
            this.InvokeAsync("saveBondedGoodsOutInfo", new object[] {
                        id,
                        pass,
                        outNo,
                        data}, this.saveBondedGoodsOutInfoOperationCompleted, userState);
        }
        
        private void OnsaveBondedGoodsOutInfoOperationCompleted(object arg) {
            if ((this.saveBondedGoodsOutInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveBondedGoodsOutInfoCompleted(this, new saveBondedGoodsOutInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saveBondedGoodsInInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string inNo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string data) {
            object[] results = this.Invoke("saveBondedGoodsInInfo", new object[] {
                        id,
                        pass,
                        inNo,
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveBondedGoodsInInfoAsync(string id, string pass, string inNo, string data) {
            this.saveBondedGoodsInInfoAsync(id, pass, inNo, data, null);
        }
        
        /// <remarks/>
        public void saveBondedGoodsInInfoAsync(string id, string pass, string inNo, string data, object userState) {
            if ((this.saveBondedGoodsInInfoOperationCompleted == null)) {
                this.saveBondedGoodsInInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveBondedGoodsInInfoOperationCompleted);
            }
            this.InvokeAsync("saveBondedGoodsInInfo", new object[] {
                        id,
                        pass,
                        inNo,
                        data}, this.saveBondedGoodsInInfoOperationCompleted, userState);
        }
        
        private void OnsaveBondedGoodsInInfoOperationCompleted(object arg) {
            if ((this.saveBondedGoodsInInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveBondedGoodsInInfoCompleted(this, new saveBondedGoodsInInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saveDomesticGoodsInInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string inNo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string data) {
            object[] results = this.Invoke("saveDomesticGoodsInInfo", new object[] {
                        id,
                        pass,
                        inNo,
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveDomesticGoodsInInfoAsync(string id, string pass, string inNo, string data) {
            this.saveDomesticGoodsInInfoAsync(id, pass, inNo, data, null);
        }
        
        /// <remarks/>
        public void saveDomesticGoodsInInfoAsync(string id, string pass, string inNo, string data, object userState) {
            if ((this.saveDomesticGoodsInInfoOperationCompleted == null)) {
                this.saveDomesticGoodsInInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveDomesticGoodsInInfoOperationCompleted);
            }
            this.InvokeAsync("saveDomesticGoodsInInfo", new object[] {
                        id,
                        pass,
                        inNo,
                        data}, this.saveDomesticGoodsInInfoOperationCompleted, userState);
        }
        
        private void OnsaveDomesticGoodsInInfoOperationCompleted(object arg) {
            if ((this.saveDomesticGoodsInInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveDomesticGoodsInInfoCompleted(this, new saveDomesticGoodsInInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saveBondedGoodsPremiumInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenceID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string data) {
            object[] results = this.Invoke("saveBondedGoodsPremiumInfo", new object[] {
                        id,
                        pass,
                        referenceID,
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveBondedGoodsPremiumInfoAsync(string id, string pass, string referenceID, string data) {
            this.saveBondedGoodsPremiumInfoAsync(id, pass, referenceID, data, null);
        }
        
        /// <remarks/>
        public void saveBondedGoodsPremiumInfoAsync(string id, string pass, string referenceID, string data, object userState) {
            if ((this.saveBondedGoodsPremiumInfoOperationCompleted == null)) {
                this.saveBondedGoodsPremiumInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveBondedGoodsPremiumInfoOperationCompleted);
            }
            this.InvokeAsync("saveBondedGoodsPremiumInfo", new object[] {
                        id,
                        pass,
                        referenceID,
                        data}, this.saveBondedGoodsPremiumInfoOperationCompleted, userState);
        }
        
        private void OnsaveBondedGoodsPremiumInfoOperationCompleted(object arg) {
            if ((this.saveBondedGoodsPremiumInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveBondedGoodsPremiumInfoCompleted(this, new saveBondedGoodsPremiumInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getDomesticGoodsOutResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute("outNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] outNo) {
            object[] results = this.Invoke("getDomesticGoodsOutResult", new object[] {
                        id,
                        pass,
                        outNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDomesticGoodsOutResultAsync(string id, string pass, string[] outNo) {
            this.getDomesticGoodsOutResultAsync(id, pass, outNo, null);
        }
        
        /// <remarks/>
        public void getDomesticGoodsOutResultAsync(string id, string pass, string[] outNo, object userState) {
            if ((this.getDomesticGoodsOutResultOperationCompleted == null)) {
                this.getDomesticGoodsOutResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDomesticGoodsOutResultOperationCompleted);
            }
            this.InvokeAsync("getDomesticGoodsOutResult", new object[] {
                        id,
                        pass,
                        outNo}, this.getDomesticGoodsOutResultOperationCompleted, userState);
        }
        
        private void OngetDomesticGoodsOutResultOperationCompleted(object arg) {
            if ((this.getDomesticGoodsOutResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDomesticGoodsOutResultCompleted(this, new getDomesticGoodsOutResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getBondedGoodsPremiumResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute("referenceID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] referenceID) {
            object[] results = this.Invoke("getBondedGoodsPremiumResult", new object[] {
                        id,
                        pass,
                        referenceID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBondedGoodsPremiumResultAsync(string id, string pass, string[] referenceID) {
            this.getBondedGoodsPremiumResultAsync(id, pass, referenceID, null);
        }
        
        /// <remarks/>
        public void getBondedGoodsPremiumResultAsync(string id, string pass, string[] referenceID, object userState) {
            if ((this.getBondedGoodsPremiumResultOperationCompleted == null)) {
                this.getBondedGoodsPremiumResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBondedGoodsPremiumResultOperationCompleted);
            }
            this.InvokeAsync("getBondedGoodsPremiumResult", new object[] {
                        id,
                        pass,
                        referenceID}, this.getBondedGoodsPremiumResultOperationCompleted, userState);
        }
        
        private void OngetBondedGoodsPremiumResultOperationCompleted(object arg) {
            if ((this.getBondedGoodsPremiumResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBondedGoodsPremiumResultCompleted(this, new getBondedGoodsPremiumResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sayHi([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("sayHi", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sayHiAsync(string arg0) {
            this.sayHiAsync(arg0, null);
        }
        
        /// <remarks/>
        public void sayHiAsync(string arg0, object userState) {
            if ((this.sayHiOperationCompleted == null)) {
                this.sayHiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsayHiOperationCompleted);
            }
            this.InvokeAsync("sayHi", new object[] {
                        arg0}, this.sayHiOperationCompleted, userState);
        }
        
        private void OnsayHiOperationCompleted(object arg) {
            if ((this.sayHiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sayHiCompleted(this, new sayHiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saveDomesticGoodsPremiumInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string referenceID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string data) {
            object[] results = this.Invoke("saveDomesticGoodsPremiumInfo", new object[] {
                        id,
                        pass,
                        referenceID,
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveDomesticGoodsPremiumInfoAsync(string id, string pass, string referenceID, string data) {
            this.saveDomesticGoodsPremiumInfoAsync(id, pass, referenceID, data, null);
        }
        
        /// <remarks/>
        public void saveDomesticGoodsPremiumInfoAsync(string id, string pass, string referenceID, string data, object userState) {
            if ((this.saveDomesticGoodsPremiumInfoOperationCompleted == null)) {
                this.saveDomesticGoodsPremiumInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveDomesticGoodsPremiumInfoOperationCompleted);
            }
            this.InvokeAsync("saveDomesticGoodsPremiumInfo", new object[] {
                        id,
                        pass,
                        referenceID,
                        data}, this.saveDomesticGoodsPremiumInfoOperationCompleted, userState);
        }
        
        private void OnsaveDomesticGoodsPremiumInfoOperationCompleted(object arg) {
            if ((this.saveDomesticGoodsPremiumInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveDomesticGoodsPremiumInfoCompleted(this, new saveDomesticGoodsPremiumInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getBondedGoodsInResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute("inNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] inNo) {
            object[] results = this.Invoke("getBondedGoodsInResult", new object[] {
                        id,
                        pass,
                        inNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBondedGoodsInResultAsync(string id, string pass, string[] inNo) {
            this.getBondedGoodsInResultAsync(id, pass, inNo, null);
        }
        
        /// <remarks/>
        public void getBondedGoodsInResultAsync(string id, string pass, string[] inNo, object userState) {
            if ((this.getBondedGoodsInResultOperationCompleted == null)) {
                this.getBondedGoodsInResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBondedGoodsInResultOperationCompleted);
            }
            this.InvokeAsync("getBondedGoodsInResult", new object[] {
                        id,
                        pass,
                        inNo}, this.getBondedGoodsInResultOperationCompleted, userState);
        }
        
        private void OngetBondedGoodsInResultOperationCompleted(object arg) {
            if ((this.getBondedGoodsInResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBondedGoodsInResultCompleted(this, new getBondedGoodsInResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getStatusData([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass) {
            object[] results = this.Invoke("getStatusData", new object[] {
                        id,
                        pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStatusDataAsync(string id, string pass) {
            this.getStatusDataAsync(id, pass, null);
        }
        
        /// <remarks/>
        public void getStatusDataAsync(string id, string pass, object userState) {
            if ((this.getStatusDataOperationCompleted == null)) {
                this.getStatusDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusDataOperationCompleted);
            }
            this.InvokeAsync("getStatusData", new object[] {
                        id,
                        pass}, this.getStatusDataOperationCompleted, userState);
        }
        
        private void OngetStatusDataOperationCompleted(object arg) {
            if ((this.getStatusDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusDataCompleted(this, new getStatusDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.insedi.or.kr/", ResponseNamespace="http://ws.insedi.or.kr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getDomesticGoodsPremiumResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute("referenceID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] referenceID) {
            object[] results = this.Invoke("getDomesticGoodsPremiumResult", new object[] {
                        id,
                        pass,
                        referenceID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDomesticGoodsPremiumResultAsync(string id, string pass, string[] referenceID) {
            this.getDomesticGoodsPremiumResultAsync(id, pass, referenceID, null);
        }
        
        /// <remarks/>
        public void getDomesticGoodsPremiumResultAsync(string id, string pass, string[] referenceID, object userState) {
            if ((this.getDomesticGoodsPremiumResultOperationCompleted == null)) {
                this.getDomesticGoodsPremiumResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDomesticGoodsPremiumResultOperationCompleted);
            }
            this.InvokeAsync("getDomesticGoodsPremiumResult", new object[] {
                        id,
                        pass,
                        referenceID}, this.getDomesticGoodsPremiumResultOperationCompleted, userState);
        }
        
        private void OngetDomesticGoodsPremiumResultOperationCompleted(object arg) {
            if ((this.getDomesticGoodsPremiumResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDomesticGoodsPremiumResultCompleted(this, new getDomesticGoodsPremiumResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getBondedGoodsOutResultCompletedEventHandler(object sender, getBondedGoodsOutResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBondedGoodsOutResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBondedGoodsOutResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void saveDomesticGoodsOutInfoCompletedEventHandler(object sender, saveDomesticGoodsOutInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveDomesticGoodsOutInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveDomesticGoodsOutInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getDomesticGoodsInResultCompletedEventHandler(object sender, getDomesticGoodsInResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDomesticGoodsInResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDomesticGoodsInResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void saveBondedGoodsOutInfoCompletedEventHandler(object sender, saveBondedGoodsOutInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveBondedGoodsOutInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveBondedGoodsOutInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void saveBondedGoodsInInfoCompletedEventHandler(object sender, saveBondedGoodsInInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveBondedGoodsInInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveBondedGoodsInInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void saveDomesticGoodsInInfoCompletedEventHandler(object sender, saveDomesticGoodsInInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveDomesticGoodsInInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveDomesticGoodsInInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void saveBondedGoodsPremiumInfoCompletedEventHandler(object sender, saveBondedGoodsPremiumInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveBondedGoodsPremiumInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveBondedGoodsPremiumInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getDomesticGoodsOutResultCompletedEventHandler(object sender, getDomesticGoodsOutResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDomesticGoodsOutResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDomesticGoodsOutResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getBondedGoodsPremiumResultCompletedEventHandler(object sender, getBondedGoodsPremiumResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBondedGoodsPremiumResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBondedGoodsPremiumResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sayHiCompletedEventHandler(object sender, sayHiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sayHiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sayHiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void saveDomesticGoodsPremiumInfoCompletedEventHandler(object sender, saveDomesticGoodsPremiumInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveDomesticGoodsPremiumInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveDomesticGoodsPremiumInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getBondedGoodsInResultCompletedEventHandler(object sender, getBondedGoodsInResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBondedGoodsInResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBondedGoodsInResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getStatusDataCompletedEventHandler(object sender, getStatusDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatusDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getDomesticGoodsPremiumResultCompletedEventHandler(object sender, getDomesticGoodsPremiumResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDomesticGoodsPremiumResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDomesticGoodsPremiumResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591